name: Release to Internal

# Run when a pull request is merged
on:
  push:
    branches:
      - main
      - 'release/*'

jobs:
  deployment:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      # Fixes the Github Action killing Gradle "Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)"
      GRADLE_OPTS: -Dorg.gradle.jvmargs="-XX:MaxMetaspaceSize=1g"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.2'
      - name: Add google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo $GOOGLE_SERVICES_JSON > app/google-services.json
          echo $GOOGLE_SERVICES_JSON > automotive/google-services.json
      - name: Add gradle.properties
        env:
          GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
        shell: bash
        run: |
          mkdir -p ~/.gradle/
          echo "${GRADLE_PROPERTIES}" > ~/.gradle/gradle.properties
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      # Mobile app
      - name: Assemble Release
        run: ./gradlew :app:bundleRelease --no-daemon
        env:
          VERSION_CODE_START: 8135
      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.SIGNING_ALIAS }}
          keyStorePassword: ${{ secrets.SIGNING_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
      - name: Upload Release
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_DEPLOY_CONFIG_JSON }}
          packageName: au.com.shiftyjelly.pocketcasts
          releaseFiles: ${{ steps.sign_app.outputs.signedReleaseFile }}
          track: internal
          status: completed
          mappingFile: app/build/outputs/mapping/release/mapping.txt
      # Automotive
      - name: Assemble Automotive Release
        run: ./gradlew assembleAutomotiveRelease bundleAutomotiveRelease --no-daemon
        env:
          VERSION_CODE_START: 58135
      - name: Sign Automotive Bundle Release
        uses: r0adkll/sign-android-release@v1
        id: sign_automotive_bundle
        with:
          releaseDirectory: automotive/build/outputs/bundle/automotiveRelease
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.SIGNING_ALIAS }}
          keyStorePassword: ${{ secrets.SIGNING_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
      - name: Sign Automotive Apk Release
        uses: r0adkll/sign-android-release@v1
        id: sign_automotive_apk
        with:
          releaseDirectory: automotive/build/outputs/apk/automotive/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.SIGNING_ALIAS }}
          keyStorePassword: ${{ secrets.SIGNING_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
      - name: Upload Automotive Release
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_DEPLOY_CONFIG_JSON }}
          packageName: au.com.shiftyjelly.pocketcasts
          releaseFiles: ${{ steps.sign_automotive_apk.outputs.signedReleaseFile }}
          track: automotive:automotive_alpha
          status: completed
          mappingFile: automotive/build/outputs/mapping/automotiveRelease/mapping.txt
      - name: Upload Automotive Apk to Github
        uses: actions/upload-artifact@v3
        with:
          name: pocket-casts-automotive-apk
          path: ${{ steps.sign_automotive_apk.outputs.signedReleaseFile }}
      # Slack
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: 'pocket-casts-dev-android-events'
          SLACK_USERNAME: 'android-internal-release'
          SLACK_ICON_EMOJI: ':rocket:'
          SLACK_MESSAGE: 'A new internal build of Pocket Casts Android is available.'
